server:
  port: 9091

spring:
  application:
    name: feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
  instance:
      statusPageUrlPath: ${management.contextPath}/info
      healthCheckUrlPath: ${management.contextPath}/health
      metadataMap:
        instanceId: ${spring.application.name}:${random.value}

feign:
  hystrix:
    enabled: true