server:
  port: 8888

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      statusPageUrlPath: ${management.contextPath}/info
      healthCheckUrlPath: ${management.contextPath}/health
      metadataMap:
        instanceId: ${spring.application.name}:${random.value}