eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1

spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/jaune/spring-cloud-config
          basedir: shop
          search-paths: shop
  application:
    name: CONFIG-SERVER

server:
  port: 8888
